### ISSUE TITLE
Classification as "none" in plsda

### ISSUE THREAD

**Issue by influence-of-canopy-on-temperature** [svkucheryavski/mdatools#117]
I am Vitor Vasconcelos, professor at the Federal University of ABC in Brazil. I am using your interesting MDAtools package in R in a research project to classify vegetation types in global scale, using the plsda() function.
  Our research team had one doubt about the classification results, and we would be very grateful if you could clarify it for us. Both in the tutorial of MDAtools and in our project results, the results of plsda() include many rows classified as "none". This was a bit perplexing for us, because usually in classification methods, we would expect the algorithm prediction to always choose one class: the one with relatively higher probability compared to the others.
  In this context, we would like to ask you if the classification as "none" is really intentional in your plsda() function. If so, what would be the criteria? And also, would there be any configuration of the parameters of the plsda() function that could force the classification to the most probable class, instead of the "none" classification?

**Comment by svkucheryavski** [comment]
Hi Vitor, the idea is as follows. As you probably know PLS-DA is based on PLS regression with dummy response variables. When you have just two classes, it simply uses a single dummy variable coded first class as 0 and second class as 1 (alternatively -1 and +1). 

But what to do if you have more than two classes? For example 3 or 4 classes? The solution in this case is as follows. For each class we use a separate response variable where 0 means "does not belong to this class" and 1 means "the class member". So if you have 4 classes, the response variable Y will be a matrix with four columns filled with dummy values. And because I want this method to be versatile and work the same way regardless how many classes you have, it does the same trick when you have two classes — create a response variable Y as a matrix with two columns. 

Then a PLS regression method is applied to predict Y-values and the predicted Y-values are subject to threshold. For example, in case if -1 and +1 values are used, the threshold is 0, if the predicted value is negative, the corresponding object does not belong to this class and if it is positive — it belongs.

But if the predicted response values are negative in all columns then the final decision is "none". Because strictly speaking it does not belong to any of the classes according to the model. There is another implementation of PLS-DA where number of columns is by 1 smaller than the number of classes. And then if all predicted y-values are negative the object is associated with the last class. 

In "mdatools" I implemented the version I described above, but you can tune it to the second version if you want. You have access to the array with predicted values, so you can implement your own decision mechanism.

There are also many other ways to make predictions, see for example: https://doi.org/10.1002/cem.3030 I plan to implement it to "mdatools" but not in the nearest future, as I am very busy these days (I work on "mdatools" in my spare time).
